name: Release builds

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.6.0

      - name: Build with PyInstaller (TradingBot)
        shell: cmd
        run: |
          pyinstaller gui\launcher.py --name TradingBot --onedir --noconsole ^
            --add-data "dashboard;dashboard" ^
            --add-data "src;src" ^
            --collect-all streamlit ^
            --collect-all plotly ^
            --collect-all yfinance ^
            --collect-all pandas ^
            --hidden-import sklearn ^
            --hidden-import scipy

          echo Listing dist:
          dir dist
          if not exist dist\TradingBot\TradingBot.exe (
            echo ERROR: dist\TradingBot\TradingBot.exe not found. Check --name and paths.
            exit /b 2
          )

      - name: Zip artifact
        shell: pwsh
        run: |
          Compress-Archive -Path "dist\TradingBot\*" -DestinationPath "TradingBot-windows.zip"

      - name: Upload Release (Windows)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            TradingBot-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.6.0

      - name: Build with PyInstaller (TradingBot)
        run: |
          pyinstaller gui/launcher.py --name TradingBot --onedir --noconsole \
            --add-data "dashboard:dashboard" \
            --add-data "src:src" \
            --collect-all streamlit \
            --collect-all plotly \
            --collect-all yfinance \
            --collect-all pandas \
            --hidden-import sklearn \
            --hidden-import scipy
          ls -la dist
          test -f "dist/TradingBot/TradingBot" || (echo "ERROR: dist/TradingBot/TradingBot not found" && exit 2)

      - name: Tar artifact
        run: |
          tar -C dist -czf TradingBot-linux.tar.gz TradingBot

      - name: Upload Release (Linux)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            TradingBot-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
